### ISSUE TITLE
Use smaller QR codes in `crowdnode-cli`

### ISSUE THREAD

**Issue by riongull** [dashhive/crowdnode.js#9]
Would be nice to have a smaller QR codes if possible/simple.

**Comment by coolaj86** [comment]
I believe this could be done using the "Conway's Game of Life" character set:
https://en.wikipedia.org/wiki/Block_Elements#Compact_table


▍ | ▐ | ▖ | ▗ | ▘ | ▙ | ▚ | ▛ | ▜ | ▝ | ▞ | ▟ | █ | ▄ | ▀ |

- upper half block
- lower half block
- right half block
- left half block
- whole block
- empty block
- the two kitty-corner quadrants
- the four exclusive corner quadrants
- the four inclusive corner quadrants

**Comment by coolaj86** [comment]
Turns out that double half and whole blocks are the solution, not the quarter blocks.

I'm glad you made the suggestion!
